name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Linting with pylint
      run: |
        make lint
    - name: Testing with pytest
      run: |
        make test
    - name: Formatting with black
      run: |
        make format
